/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-24 at 19:54:18 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.tictactoe.model;

/**
 * ProtoRPC container for users.User objects. Attributes: email: String; The email of the user.
 * auth_domain: String; The auth domain of the user. user_id: String; The user ID.
 * federated_identity: String; The federated identity of the user.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UserMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("auth_domain")
  private java.lang.String authDomain;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("federated_identity")
  private java.lang.String federatedIdentity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("user_id")
  private java.lang.String userId;

  /**
   * @return value or {@code null} for none
   */
  public String getAuthDomain() {
    return authDomain;
  }

  /**
   * @param authDomain authDomain or {@code null} for none
   */
  public UserMessage setAuthDomain(String authDomain) {
    this.authDomain = authDomain;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public UserMessage setEmail(String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getFederatedIdentity() {
    return federatedIdentity;
  }

  /**
   * @param federatedIdentity federatedIdentity or {@code null} for none
   */
  public UserMessage setFederatedIdentity(String federatedIdentity) {
    this.federatedIdentity = federatedIdentity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public UserMessage setUserId(String userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public UserMessage set(String fieldName, Object value) {
    return (UserMessage) super.set(fieldName, value);
  }

  @Override
  public UserMessage clone() {
    return (UserMessage) super.clone();
  }

}
